# FROM remote-docker-elastic.artifactory.danskenet.net/logstash/logstash:7.15.1
FROM docker.elastic.co/logstash/logstash:7.15.1
COPY logstash.yml /usr/share/logstash/config/logstash.yml
COPY logstash.conf /usr/share/logstash/pipeline/logstash.conf
USER root
RUN chown root:logstash /usr/share/logstash/config/logstash.yml
RUN chown root:logstash /usr/share/logstash/pipeline/logstash.conf
USER logstash